### ISSUE TITLE
Drop Zone is not working

### ISSUE THREAD

**Issue by po3nx** [DevExpress-Examples/DataGrid---How-to-use-FileUploader-in-an-edit-form#1]
Thanks for the example, I'm trying to implement this sample for my VueJS Application, all work as expected except the dropzone, when I try to drag the file into the drop zone area, it immediately disappear, no upload process and the file seems not catched by drop zone, even when I build using this example source code, it also not working , kindly please help
 thank you

**Comment by LexDX** [comment]
Hi @po3nx,

Please submit your question to our Support Center ([https://devexpress.com/sc](https://devexpress.com/sc)) and describe the issue in greater detail. We will be happy to help you resolve this issue.
